### ISSUE TITLE
meta: setup continuous benchmarking

### ISSUE THREAD

**Issue by ankush** [frappe/caffeine#42]
1. [x] Get a new bare metal server
2. [x] Do some A/A tests ensure <1% variance
3. [x] Setup self hosted GHA runner
4. [ ] Write an action for benchmarking - nightly + dispatch
5. [ ] Do some A/A testing with GHA setup.
6. [x] Add custom metadata to `pyperf`'s JSON output.
7. [ ] Evaluate bencher v. custom insights based solution
7. [ ] Establish a baseline with this commit https://github.com/frappe/frappe/commit/7c06c845ea345a67fec66d0321dedf9a1bbc2152
8. [ ] Run benchmarks nightly
9. [ ] Upload data _somewhere_
10. [ ] Ensure concurrency of 1
11. [ ] Dashboards, pretty charts
12. [ ] Alerts

**Comment by epompeii** [comment]
@ankush you may want to check out Bencher: https://github.com/bencherdev/bencher

Bencher supports 2, 3, 5, & 6 out of the box, for free for public projects. Points 1 & 4 [are also available](https://bencher.dev/pricing/#bare-metal). I'm the maintainer of Bencher, so I would be more than happy to help answer any questions.
